n = input('Digite o algo: ')
print('o valor digitado é um "isalnum": ', n.isalnum())
print('o valor digitado é um "isnumeric": ', n.isnumeric())
print('o valor digitado é um "isalpha": ', n.isalpha())
print('o valor digitado é um "isascii": ', n.isascii())
print('o valor digitado é um "isdigit": ', n.isdigit())
print('o valor digitado é um "isdecimal": ', n.isdecimal())
print('o valor digitado é um "isidentifier": ', n.isidentifier())
print('o valor digitado é um "islower": ', n.islower())
print('o valor digitado é um "isprintable": ', n.isprintable())
print('o valor digitado é um "isspace": ', n.isspace())
print('o valor digitado é um "istitle": ', n.istitle())
print('o valor digitado é um "isupper": ', n.isupper())
