a = input('Digite o algo: ')
print('O tipo primitivo digitado é ', type(a))
print('o valor digitado é um "isalnum": ', a.isalnum())
print('o valor digitado é numerico: ', a.isnumeric())
print('o valor digitado é alphanumerico": ', a.isalpha())
print('o valor digitado é um "isascii": ', a.isascii())
print('o valor digitado é um "isdigit": ', a.isdigit())
print('o valor digitado é decimal: ', a.isdecimal())
print('o valor digitado é um "isidentifier": ', a.isidentifier())
print('o valor digitado esta em minusculo: ', a.islower())
print('o valor digitado é um "isprintable": ', a.isprintable())
print('o valor digitado é espaço: ', a.isspace())
print('o valor digitado esta capitalizado: ', a.istitle())
print('o valor digitado esta em maiusculo: ', a.isupper())
